### ISSUE TITLE
Prethoryn Scourge hits my barren world colonies and converts them into infested-type worlds...

### ISSUE THREAD

**Issue by jacksondus** [Thomahawk2k/Colonize-Unlimited#8] opened 2016-06-23 21:56 UTC
This seems rather weird to me and might not be a bug, but the scourge landed on my Mars colony and purged my synth pops, turning it into an infested-type world. I was under the impression that the Prethoryns required suitable atmospheric conditions for life in general.

**Comment by dosaki** [comment] 2016-06-24 10:31
I haven't had that disaster yet. TBH I've never really monitored what disaster races did on their planets.

Maybe they have habitability 100% everywhere? Not sure.

**Comment by jacksondus** [comment] 2016-06-29 18:56
@dosaki  I modded CK2 for a while, though only for my own personal use, so here are some ideas. I could understand this for barren worlds to some defgree, but I get gas-giant to infested to barren transitions as well, which is wierd. Perhaps we could add an infested-type world for all planet classes (pc_infested_gas_giant). I am not into graphics though, so perhaps we could create a flag-based system (flagging a planet with flag flag_pc_gas_giant) or something like that?

**Comment by dosaki** [comment] 2016-06-29 20:03
That sounds like a good idea.

I'm closing this issue and opening a new one (#9) related to that as I believe the original problem is not a bug.

**Closed as completed by dosaki** 2016-06-29 20:03 UTC
Labels: question
